# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TCP-Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  pod 'TCP', :path => './../'

  target 'TCP-DemoTests' do
    inherit! :search_paths
    #pod 'CocoaAsyncSocket'
  end

end
